# Generated by Django 3.1.7 on 2021-03-04 14:01

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_machine_spare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='spares',
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[bboard.models.validate_even], verbose_name='Цена'),
        ),
        migrations.DeleteModel(
            name='AdvUser',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Spare',
        ),
    ]
